/**
 * Generated by `npm run assets:ambient` — do not edit by hand.
 */

export interface AmbientSceneFiles {
  soundSeconds: number;
  posterWidths: readonly number[];
  /** % of the width kept on a portrait screen. */
  focalX: number;
  /** The browser toolbar's colour while this scene shows. */
  chrome: string;
  lqip: string;
}

export const AMBIENT_MANIFEST: Record<'coast' | 'forest' | 'snow', AmbientSceneFiles> = {
  "coast": {
    "posterWidths": [
      960,
      1920
    ],
    "focalX": 42,
    "chrome": "#544b42",
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAwCdASogABIAPu1kqU2ppaOiMAgBMB2JZwCw7A8DYRp1d6ZAAMsN3ZKxchGm7M+qk9hiCBdOIfRvHotIJ/FEA8C0yJBCEUiM8NpRHAQAAA==",
    "soundSeconds": 360
  },
  "forest": {
    "posterWidths": [
      960,
      1920
    ],
    "focalX": 54,
    "chrome": "#161616",
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQBACdASogABIAPu1mpk2ppaMiMBgMATAdiWUAtsg0cKyungQ8znC9pA3gAP7vRZ9kCeAhUnd6r2qDGHZU76cDFY+lwdyV7NQI9Htxh2nq6vlv/rb45Bnktcw7s8zopj+PdFNSgAA=",
    "soundSeconds": 280
  },
  "snow": {
    "posterWidths": [
      960,
      1920
    ],
    "focalX": 28,
    "chrome": "#5c656e",
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQBACdASogABIAPu1mq06ppaQiKA1RMB2JZwCw7BB2yhFH0uNYRNLWx70YAP7DSTR97GCTQMScZ3UvAGkTTzyzRM5BcrLw5dWDUY0gVRlDp4bc7uN/sldnFsM76j068GC8Wu/WYUFazZiAAAA=",
    "soundSeconds": 270
  }
};
