/**
 * Generated by `npm run assets:ambient` — do not edit by hand.
 */

export interface AmbientSceneFiles {
  soundSeconds: number;
  posterWidths: readonly number[];
  /** % of the width kept on a portrait screen. */
  focalX: number;
  /** The browser toolbar's colour while this scene shows. */
  chrome: string;
  lqip: string;
  /** The moving loop's file stem under /audio, or null for a still. */
  loop: string | null;
}

export const AMBIENT_MANIFEST: Record<'coast' | 'forest' | 'snow', AmbientSceneFiles> = {
  "coast": {
    "posterWidths": [
      960,
      1920
    ],
    "focalX": 55,
    "chrome": "#283042",
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBQCdASogABIAPu1qqU6ppiOiMBgIATAdiWQAnTLiyqrgweA5LZsqLYdBsZIRp+te+7cAAP6wl7lDbZnnV2wZgIBh1HivhbPOQJHhdu6GFrgNImjUDp1tCUjT86/M+cF3+HU3cpQjz9uegPm/a90yvPjCAmdC70kNt0n7WcsToWnX83gAAA==",
    "loop": "ambient-coast-beaf6b3e",
    "soundSeconds": 222
  },
  "forest": {
    "posterWidths": [
      960,
      1920
    ],
    "focalX": 55,
    "chrome": "#655c54",
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACQBACdASogABIAPu1mqU2ppaOiMAgBMB2JZwDE2BinVQnrUqiH/7Y8Qj/0cFAA/tsiZkD0eXOBBeVPCYedH+DWKAjyd1Kh4fC/lezl16RnnEDAMGv0j6oogMRQGV2shVQAAA==",
    "soundSeconds": 280,
    "loop": null
  },
  "snow": {
    "posterWidths": [
      960,
      1920
    ],
    "focalX": 15,
    "chrome": "#424242",
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwBACdASogABIAPu1qrE8ppiQiMBgIATAdiWcAyjMhgJfkL8u37NT7VxQAhMGtG4T4gv6s9WKTenNLZv6HlMkI91mB1X3lbflHAKy6mdgegNFOwAAAAA==",
    "loop": "ambient-snow-2457fdd9",
    "soundSeconds": 270
  }
};
