/**
 * Generated by `npm run assets:audio` — do not edit by hand.
 *
 * Each channel's programme, in order. Durations are read from the files
 * themselves; they are what every visitor uses to work out where the shared
 * programme currently is.
 */

export interface ManifestTrack {
  src: string;
  durationSeconds: number;
  /** From the file's own tags, for the licensing note. Not shown in the UI. */
  title: string | null;
}

export const AUDIO_MANIFEST: Record<string, readonly ManifestTrack[]> = {
  still: [
    {
      src: "/audio/Still%201.mp3",
      durationSeconds: 2626.344,
      title: "Still 1",
    },
    {
      src: "/audio/Still%202.mp3",
      durationSeconds: 3695.464,
      title: "Still 2",
    },
  ],
  flow: [
    {
      src: "/audio/Flow%201.mp3",
      durationSeconds: 3639.816,
      title: "Flow 1",
    },
    {
      src: "/audio/Flow%202.mp3",
      durationSeconds: 3646.848,
      title: "Flow 2",
    },
    {
      src: "/audio/Flow%203.mp3",
      durationSeconds: 3815.497,
      title: "Flow 3",
    },
  ],
  momentum: [
    {
      src: "/audio/Momentum%201.mp3",
      durationSeconds: 3724.896,
      title: "Momentum 1",
    },
    {
      src: "/audio/Momentum%202.mp3",
      durationSeconds: 3708.735,
      title: "Momentum 2",
    },
    {
      src: "/audio/Momentum%203.mp3",
      durationSeconds: 3694.55,
      title: "Momentum 3",
    },
  ],
};
