/**
 * Generated by `npm run assets:audio` — do not edit by hand.
 *
 * Each channel's programme, in order. Durations are read from the files
 * themselves; they are what every visitor uses to work out where the shared
 * programme currently is.
 */

export interface ManifestTrack {
  src: string;
  durationSeconds: number;
  /** From the file's own tags, for the licensing note. Not shown in the UI. */
  title: string | null;
}

export const AUDIO_MANIFEST: Record<string, readonly ManifestTrack[]> = {
  still: [
    {
      src: "/audio/Still%201.m4a",
      durationSeconds: 2626.343,
      title: "Still 1",
    },
    {
      src: "/audio/Still%202.m4a",
      durationSeconds: 3695.456,
      title: "Still 2",
    },
  ],
  flow: [
    {
      src: "/audio/Flow%201.m4a",
      durationSeconds: 3639.815,
      title: "Flow 1",
    },
    {
      src: "/audio/Flow%202.m4a",
      durationSeconds: 3646.847,
      title: "Flow 2",
    },
    {
      src: "/audio/Flow%203.m4a",
      durationSeconds: 3815.48,
      title: "Flow 3",
    },
  ],
  momentum: [
    {
      src: "/audio/Momentum%201.m4a",
      durationSeconds: 3724.895,
      title: "Momentum 1",
    },
    {
      src: "/audio/Momentum%202.m4a",
      durationSeconds: 3708.714,
      title: "Momentum 2",
    },
    {
      src: "/audio/Momentum%203.m4a",
      durationSeconds: 3694.527,
      title: "Momentum 3",
    },
  ],
};
