/**
 * Generated by `npm run assets:images` — do not edit by hand.
 *
 * One entry per image in /design-reference. `focalX` is where the crop
 * centres when the viewport is portrait; `lqip` is the blurred placeholder,
 * inlined so the first paint is already warm.
 */

export interface ManifestRoom {
  id: string;
  widths: readonly number[];
  focalX: number;
  lqip: string;
}

export const BACKGROUND_MANIFEST: readonly ManifestRoom[] = [
  {
    id: "cafe-concrete-hall",
    widths: [640, 1024, 1600],
    focalX: 50,
    lqip: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBQCdASogABIAPuFWpU2opKOiN/qoARAcCWcAygAWy00iEEs+2EIT4gj7ZD/ZUIUAAP7NdnKR2pEJ+h0pyD+3mJTyrdyg112NLOoZN27nxk761uliVhnewaOXfC9/45UVKWwbSksAAAAA",
  },
  {
    id: "cafe-garden-door",
    widths: [640, 1024, 1600],
    focalX: 68,
    lqip: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwBQCdASogABIAPu1kq04ppaQiKA1RMB2JZwDE2A8VRMcyHneo7fho22FqyoE+/LHrAAD+o1TKOXE26unAQhoFYURyz6RTp0K5MFJ6ZTBKqivvx8B8WDUGDKFPE2XkiWRehnH0MhaLUAAA",
  },
  {
    id: "cafe-windows",
    widths: [640, 1024, 1600],
    focalX: 32,
    lqip: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBQCdASogABIAPuVipk2pJaOiMAwBIByJZwDCgB2O7PwpdkJoxyINwJE3CAx4q0YAAP7rGLNMJLGetfUPbVm7kihAoNoVBGbD3mhepsEDkIIPmwsmRGGk+EkzyvQVzNMOB6xFbIISsRYmyT26AAAA",
  },
  {
    id: "cliff-cave",
    widths: [640, 1024, 1600],
    focalX: 50,
    lqip: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwBQCdASogABIAPuFeqk2opSQiMAwBEBwJZQC2yCIgt+7ELhLJ8r+T3bEnkYNz2sLw7l2gAP6+K5zHYEK88xWy3WDEfnVzd7TLse3eZJ5wtnDJ02Hzyo1/r3phdZW9WfUA20fO3u33a7dl8C4ogAAA",
  },
  {
    id: "desert-arches",
    widths: [640, 1024, 1600],
    focalX: 42,
    lqip: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQBACdASogABIAPu1kqE4ppaOiMAgBMB2JZQCw7BjF0g9iJcQzsyX6yfS3uTScgAD+zrWj+dbTX/9pyqvqH6r8kBmEHvpkde0mBTLdkYnaG5pDHCac1maXoM5BWI3AYxX5Rn24HMpRilQA",
  },
  {
    id: "garden-pool",
    widths: [640, 1024, 1600],
    focalX: 66,
    lqip: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQBACdASogABIAPu1mq04ppaQiMAgBMB2JZQC2yCFoUFbAMkzwnCJ0WQSkemlasAD+7ov2KavS/hRIE2QlTnj/CN1NADUWdGs0KtMvxNPj3l2K93YqUdFHqOSfYPzr7+AqZL8dp1PoFZzy/rJpVl7gAAA=",
  },
  {
    id: "oculus-courtyard",
    widths: [640, 1024, 1600],
    focalX: 68,
    lqip: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwBQCdASogABIAPu1ip02ppaMiMBgMATAdiWUAxnwPSmd1vXJX3nryfOzxjpD9HhMJvRZQAP7Qw6CaVY6VsLxOnmTeBtlJmBQHQeGa3v1SmmW+yXRWjmFkkLiYTLB9wSEMkpHpV8d7EC+flEp5wAAA",
  },
  {
    id: "valley-vault",
    widths: [640, 1024, 1600],
    focalX: 34,
    lqip: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBQCdASogABIAPu1ssFCppiSiqAqpMB2JZQCw7A9au02rVmK5yB5G00AofxyiuwOgAMyeOhd8Yi6QCoQtpuRXNM1D5MYDPhcn5SHQDttplOY25dnCI/MSuntI1ruM5ZU2+yNeiXhYj2jryqlyYGvxQPtKAAAA",
  },
];
