/**
 * Generated by `npm run assets:images` — do not edit by hand.
 *
 * One entry per image in /design-reference. `focalX` is where the crop
 * centres when the viewport is portrait; `lqip` is the blurred placeholder,
 * inlined so the first paint is already warm.
 */

export interface ManifestRoom {
  id: string;
  widths: readonly number[];
  focalX: number;
  lqip: string;
}

export const BACKGROUND_MANIFEST: readonly ManifestRoom[] = [
  {
    id: "alpine-lake-studio",
    widths: [640, 1024, 1600],
    focalX: 68,
    lqip: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQBACdASogABIAPu1mq08ppaOiKA1RMB2JZwC7AA3iP+oEJ7zBs36sBx40nzAA/uc5uCsE6srHjR6fYVAj2gUZlb3RY3KPxL2VzddSXuvSpL8ECcD6nspoZCx1rhQ8R6aNnL+95DobrAvGAAA=",
  },
  {
    id: "cafe-concrete-hall",
    widths: [640, 1024, 1600],
    focalX: 50,
    lqip: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBQCdASogABIAPuFWpU2opKOiN/qoARAcCWcAygAWy00iEEs+2EIT4gj7ZD/ZUIUAAP7NdnKR2pEJ+h0pyD+3mJTyrdyg112NLOoZN27nxk761uliVhnewaOXfC9/45UVKWwbSksAAAAA",
  },
  {
    id: "cafe-garden-door",
    widths: [640, 1024, 1600],
    focalX: 68,
    lqip: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwBQCdASogABIAPu1kq04ppaQiKA1RMB2JZwDE2A8VRMcyHneo7fho22FqyoE+/LHrAAD+o1TKOXE26unAQhoFYURyz6RTp0K5MFJ6ZTBKqivvx8B8WDUGDKFPE2XkiWRehnH0MhaLUAAA",
  },
  {
    id: "cafe-windows",
    widths: [640, 1024, 1600],
    focalX: 32,
    lqip: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBQCdASogABIAPuVipk2pJaOiMAwBIByJZwDCgB2O7PwpdkJoxyINwJE3CAx4q0YAAP7rGLNMJLGetfUPbVm7kihAoNoVBGbD3mhepsEDkIIPmwsmRGGk+EkzyvQVzNMOB6xFbIISsRYmyT26AAAA",
  },
  {
    id: "calm-ocean-screen",
    widths: [640, 1024, 1600],
    focalX: 65,
    lqip: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwBQCdASogABIAPu1opU2ppqMiMBgMATAdiWUAnTLHQaoLijQEufs00kwwowKZpeIj3YNgAPa9Uz9P01bVKnywLycIc7bcbMcRJUskrAGT2et7Sl5x7tXPLs4vIt+LW/aOjl3RRSMY8AAA",
  },
  {
    id: "calm-screen-working",
    widths: [640, 1024, 1600],
    focalX: 43,
    lqip: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwBACdASogABIAPu1mqk2ppaQiMAgBMB2JYwC06BHoW1uR3q32PKMnaJLwWyEcEOgAeMMLZBp5WmF+9TwJrbEKaaeh0LAPqsfGai7WRjuakn4jVlP+y3ootueJaLvIU5b+LeuiooDAswCYAAA=",
  },
  {
    id: "circular-window-studio",
    widths: [640, 1024, 1600],
    focalX: 65,
    lqip: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQBACdASogABIAPu1kqU2ppaQiMAgBMB2JZwDGQB6IpNs5tB83PsZftX56DuTyMADgIOGxsOtDDOTQtWazvSpZga8jeqRsVEfOVdGSbaShrwDEmdKK6jwbCD3XmomJkYcm/ayOCAA=",
  },
  {
    id: "cliff-cave",
    widths: [640, 1024, 1600],
    focalX: 50,
    lqip: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwBQCdASogABIAPuFeqk2opSQiMAwBEBwJZQC2yCIgt+7ELhLJ8r+T3bEnkYNz2sLw7l2gAP6+K5zHYEK88xWy3WDEfnVzd7TLse3eZJ5wtnDJ02Hzyo1/r3phdZW9WfUA20fO3u33a7dl8C4ogAAA",
  },
  {
    id: "coastal-observatory",
    widths: [640, 1024, 1600],
    focalX: 74,
    lqip: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBQCdASogABIAPu1ipU4ppSMiMBgMATAdiWcAwcwL1ILDDkPXKTOrmTGJm2PDxnVvcAD7Izonbx7AD+83aI1fqlul6aq5/JcHzJvp3rs6vF6GCCFML63euSL+H2CUJ7IJMgkwQ6B9nSO8Ocsg1AAA",
  },
  {
    id: "desert-arches",
    widths: [640, 1024, 1600],
    focalX: 42,
    lqip: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQBACdASogABIAPu1kqE4ppaOiMAgBMB2JZQCw7BjF0g9iJcQzsyX6yfS3uTScgAD+zrWj+dbTX/9pyqvqH6r8kBmEHvpkde0mBTLdkYnaG5pDHCac1maXoM5BWI3AYxX5Rn24HMpRilQA",
  },
  {
    id: "desert-rock-pavilion",
    widths: [640, 1024, 1600],
    focalX: 60,
    lqip: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwBACdASogABIAPu1mq04ppaQiMAgBMB2JZQDE2BALd6GCPMneG0D46AMMkhsgAP0cP5UHjWHbc8JX5PIxKDywtkT7zVH9ZxxdYv80TFxwkUmukXU8RqmD3ykY5JG23GDLxMgAAAA=",
  },
  {
    id: "forest-console-invitation",
    widths: [640, 1024, 1600],
    focalX: 50,
    lqip: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwBACdASogABIAPuFcqU2opSQiMAwBEBwJZQC/7CHe1zKdh/cLa0lbQ73yS7cIAP7o6HTL6VqBdhLP2QfCQkEpGRvyBD+pRTWWQ+ZESvLP88bx5Yks2OHAAAA=",
  },
  {
    id: "garden-pool",
    widths: [640, 1024, 1600],
    focalX: 66,
    lqip: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQBACdASogABIAPu1mq04ppaQiMAgBMB2JZQC2yCFoUFbAMkzwnCJ0WQSkemlasAD+7ov2KavS/hRIE2QlTnj/CN1NADUWdGs0KtMvxNPj3l2K93YqUdFHqOSfYPzr7+AqZL8dp1PoFZzy/rJpVl7gAAA=",
  },
  {
    id: "mountain-cavern",
    widths: [640, 1024, 1600],
    focalX: 55,
    lqip: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQBACdASogABIAPu1ip02ppaMiMBgMATAdiWcAyNQNE3O6IRgKqJQihMwwhuLk8AD+2VkZEEU5siKmNAbEQE6obJKoPqAelcic6AQtOJUehPdHP6MbZGHjJoW/tgVDb6gAAAAA",
  },
  {
    id: "ocean-workstation-invitation",
    widths: [640, 1024, 1600],
    focalX: 68,
    lqip: "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwBACdASogABIAPu1kqU2ppaQiMAgBMB2JQBdmbIBpuIV/ee+0OX3Y5J4oec3kQIAA/sHJWQGJtVeYPn27GeyB70rd13eJuHwdtTzk90t8J0S9t+bkodm24E9Fg6Mpp6tYE2WvkRSQ0y4V5mXzIoAGxfyAAA==",
  },
  {
    id: "oculus-courtyard",
    widths: [640, 1024, 1600],
    focalX: 68,
    lqip: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwBQCdASogABIAPu1ip02ppaMiMBgMATAdiWUAxnwPSmd1vXJX3nryfOzxjpD9HhMJvRZQAP7Qw6CaVY6VsLxOnmTeBtlJmBQHQeGa3v1SmmW+yXRWjmFkkLiYTLB9wSEMkpHpV8d7EC+flEp5wAAA",
  },
  {
    id: "open-ocean-reading-room",
    widths: [640, 1024, 1600],
    focalX: 16,
    lqip: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQBACdASogABIAPuVipE2pJaMiMAwBIByJZwDCgBP6daKCoPBgUDogiYvnInAA/VCZ7CAebzTNB4rSpmdesU0g5Z4+Dq8FkhRWZNxoAYYsTPxJ6NW+fQ6rwuOynzhF0tzPacAA",
  },
  {
    id: "rain-garden-pavilion",
    widths: [640, 1024, 1600],
    focalX: 64,
    lqip: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQBACdASogABIAPu1kqE2ppaOiMAgBMB2JYwDCgB5e8rW4/agZydfRiOAT3eg0MAD+2X+VcMDmgnZh+nTwf8TNFLlGjmmbuy9WKOisrQwPTarsFZk6q0YPu9h28HDP101nHZqE20AAAA==",
  },
  {
    id: "valley-vault",
    widths: [640, 1024, 1600],
    focalX: 34,
    lqip: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBQCdASogABIAPu1ssFCppiSiqAqpMB2JZQCw7A9au02rVmK5yB5G00AofxyiuwOgAMyeOhd8Yi6QCoQtpuRXNM1D5MYDPhcn5SHQDttplOY25dnCI/MSuntI1ruM5ZU2+yNeiXhYj2jryqlyYGvxQPtKAAAA",
  },
];
