/** Generated by `npm run assets:journal` — do not edit by hand. */

export interface JournalPhotoEntry {
  id: string;
  widths: readonly number[];
  lqip: string;
}

export const JOURNAL_PHOTOS: readonly JournalPhotoEntry[] = [
  {
    "id": "body-doubling",
    "widths": [
      640,
      1024,
      1600,
      2048
    ],
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASogAA0APu1oqk6ppiQiMAgBMB2JZACdABPNKOVuXc1kgAAA/p7sucJ691Kht13ULLf5b0OUrzdP5PXCrUe+6K0ycoFM1HXmASwcmX7Fm1nYX6+7V3F+f/m9ol1u9gslafU0XQAA"
  },
  {
    "id": "how-to-take-a-real-break",
    "widths": [
      640,
      1024,
      1600,
      2048
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASogAA0APu1iqk2ppaQiMAgBMB2JZACdAB2Oqn6h1lhKuZAA/i3DfI3zahDYgvHI0Fhygna6GuHRyLaZzhRCBht8Ecng1fqTPEolQzKKH1X70nAA"
  },
  {
    "id": "music-for-focus",
    "widths": [
      640,
      1024,
      1600,
      2048
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASogAA0APu1iqk2ppaQiMAgBMB2JYgCdMoR4GB4nm4ELA7tlhyAA/qSmtQNQebkcrx4JrdTX8KodyAW/HcUmpFLSBfBBWzpLS4losuHjzgKwSz7XQTkFlunACf1bDE6kibbmjBeB4mbCgAAA"
  },
  {
    "id": "one-line-morning-routine-hero",
    "widths": [
      640,
      1024,
      1600,
      2048
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASogAAsAPu1kqk2ppaQiMAgBMB2JQBOmUAE1fWYdJ7LSAn5yoAAA/vKyUVo4YZMHhZj6WH1StCwHwVlpxroUyj6U6oG3ANB8HDRqjkeJHq1opk7oHZ35fgAA"
  },
  {
    "id": "one-line-morning-routine",
    "widths": [
      640,
      1024,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBQCdASogABUAPu1kqU2ppaOiMAgBMB2JQBOmZl1shP1kN/6SGbKALM5zMGQd1CvAAP678bfThDeFufyKPh2llqXTBB4nqpBv9FfT8lL6GT7XSOP0tut5b/Vp86/YbORN92ICIyiy4aCGHJzAuEdWn8ngmtyJmrxRwtk9omrDu+grgUpAKxydaq6UAA=="
  },
  {
    "id": "pomodoro-technique-gently",
    "widths": [
      640,
      1024,
      1600,
      2048
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASogAA0APu1mq04ppaQiMAgBMB2JQBOgAtX2gX4MQyVNwsAAx/DzcezKQ/6KU8shkEuIjGExb+npM9QObU/AzXLnzohS+rCHJvPoJ303cUaf8RQA"
  }
];
